name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Install tools
      run: dotnet tool install --global coverlet.console

    - name: Build Release
      run: dotnet build --configuration Release --no-restore

    - name: Build Debug
      run: dotnet build --configuration Debug --no-restore

    - name: Testing Palindromo
      run: coverlet Palindromo/Palindromo.UnitTests/bin/Debug/netcoreapp3.0/Palindromo.UnitTests.dll --target "dotnet" --targetargs "test Palindromo/Palindromo.UnitTests/Palindromo.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output palindromo.coverage.xml

    - name: Upload
      run: bash <(curl -s https://codecov.io/bash)
